name: Bench

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'coq-tactician'
      - uses: actions/checkout@v2
        with:
          repository: 'coq-tactician/coq-tactician-stdlib'
          ref: 'coq8.11'
          path: 'coq-tactician-stdlib'
      - uses: coq-community/docker-coq-action@v1.1.0
        with:
          opam_file: 'coq-tactician.opam'
          coq_version: '8.11'
          ocaml_version: '4.09-flambda'
          custom_script: |
