name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1.1.0
        with:
          opam_file: 'coq-tactician.opam'
          coq_version: '8.11'
          ocaml_version: '4.09-flambda'
